### ISSUE TITLE
Parent constructor name displayed when extending from some built-in objects

### ISSUE THREAD

**Issue by mootari** [observablehq/inspector#134]
For instances of classes that extend built-objects like Event, EventTarget and Error (and any of their children), the Inspector will display the name of the parent class.

Demo: https://observablehq.com/d/8f5b8f5c3518e1b5

**Comment by mootari** [comment]
Seems to me that in https://github.com/observablehq/inspector/blob/ed6eb87359596e4d25ae75b22598c7a2cd3e585e/src/object.js#L12-L16 the check for constructor should come first.

**Comment by mootari** [comment]
Looks like this behavior is consistent with how objects are displayed in the console, and I assume that consistency was the primary goal. Closing, and sorry for the noise.

**Comment by mbostock** [comment]
It’s because these built-in objects define a Symbol.toStringTag. If you want to extend them and provide a different string tag, try this:

```js
class MyEvent extends CustomEvent {
  [Symbol.toStringTag] = "MyEvent";
}
```
