### ISSUE TITLE
`RuntimeError: Unknown require resource. Please add it to knownExternalResources list, so that they can be statically resolved for report archival`

### ISSUE THREAD

**Issue by TheeMattOliver** [observablehq/inspector#188]
Seeing this in some notebooks today.

```viewof selectedMetric = RuntimeError: Unknown require resource. Please add it to knownExternalResources list, so that they can be statically resolved for report archival: https://cdn.jsdelivr.net/npm/@observablehq/inspector@5.0.1/dist/inspector.js```

Example:

https://observablehq.com/@smoogly/design-system-metrics

**Comment by mootari** [comment]
The error message is produced by the notebook and unrelated to this library: https://observablehq.com/@smoogly/design-system-metrics/safe#require
