### ISSUE TITLE
isUTCMidnight makes for noticeably odd behavior

### ISSUE THREAD

**Issue by jashkenas** [observablehq/inspector#50]
We use [an `isUTCMidnight()` sniff](https://github.com/observablehq/inspector/blob/master/src/formatDate.js#L6-L11) to swap out the inspected behavior of date objects ... which leads to strangeness when a user happens to land on midnight accidentally:

https://talk.observablehq.com/t/odd-date-behaviour-when-setting-hour-to-17/2125

![image](https://user-images.githubusercontent.com/4732/60845985-d3aae400-a192-11e9-95a1-6820da556620.png)

**Comment by mbostock** [comment]
Special-casing UTC midnight is useful for a variety of reasons (such as input type=date). We could always format dates as UTC, but that would make it harder to read local times.

**Comment by jashkenas** [comment]
Totally. Without a reified way to know the intent of the use of the date (as a date, or as a time) — I can't think of a good way for us to make this better.

**Comment by mbostock** [comment]
For future reference, here’s the part of the spec that lead to this behavior, [20.3.3.2 Date.parse(string)](https://tc39.es/ecma262/#sec-date.parse):

> When the UTC offset representation is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as a local time.

The “UTC offset representation” is Z.
